name: ai-architecture-template
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - pylint
  - pip:
    - papermill
    - azureml-core
    - pylint-junit
    - git+https://github.com/microsoft/AI-Utilities.git@version/0.2.0
