name: ai-architecture-template
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - urllib3
  - pytest
  - pylint
  - pip:
    - azure-cli
    - papermill
    - python-dotenv
    - azureml-core==1.0.57
    - git+https://github.com/microsoft/AI-Utilities.git@version/0.2.0
